### ISSUE TITLE
Getting error when trying to access `published` attribute of the feed item

### ISSUE THREAD

**Issue by oussama-he** [rowanmanning/feed-parser#123]
I'm getting the error below when trying to access the `published` attribute of the feed item:
```
Uncaught Error: `new Date()` with non-number arguments is not supported.
    at get textContentAsDate [as textContentAsDate] (../../node_modules/@rowanmanning/feed-parser/lib/xml/element.js:207:3)
    at get published [as published] (../../node_modules/@rowanmanning/feed-parser/lib/feed/item/rss.js:66:1)
```

My code looks like this:
```js
const projects = [];

    for (let item of parseFeed(feed).items) {
      projects.push({
        'title': `${item.title}`,
        'description': `${item.description}`,
        'url': `${item.url}`,
        'pubDate': `${item.published}`
      })
    }
```

**Comment by rowanmanning** [comment]
Hi 👋 could you share the feed that you're trying to parse?

**Comment by oussama-he** [comment]
I'm trying to parse this feed:
https://mostaql.com/rss

**Comment by rowanmanning** [comment]
Odd I'm unable to replicate this, the feed parses fine for me and I'm able to access the `published` property of all items. Could you let me know the following:

* Node.js version
* Version of the `@rowanmanning/feed-parser` library you have installed
* The rest of your code above this point, e.g. how do you populate the `feed` variable?

**Comment by oussama-he** [comment]
Thank you for your response and sorry to be late.

When you asked me about the Node.js version, I checked the runtime version used in the service I'm using. I found that they use by default a custom JavaScript runtime very similar to the Cloudflare Workers runtime. When I changed it to Node.js runtime the error disappeared.
