### ISSUE TITLE
Example using import statements (for ES6 or ECMAScript)

### ISSUE THREAD

**Issue by pietheinstrengholt** [rowanmanning/feed-parser#141]
Hi Rowan,

I'm currently using Feedparser by danmactough. The package works great, but isn't maintained anymore. Is your intend to offer something similar? In this respect? Can feed-parser also be used using import statements? If so, it would be nice to provide an example. Thanks!

**Comment by rowanmanning** [comment]
Hi @pietheinstrengholt 👋 yep I'm intending on maintaining this for the forseeable future. I also used to use danmactough's library and this is partially inspired by it.

You can use import statements, [I've added an example to the README](https://github.com/rowanmanning/feed-parser#usage). This should work:

```js
import { parseFeed } from '@rowanmanning/feed-parser';
```

Something to bear in mind (it mentions in the README too) is that this library doesn't _fetch_ the feed - it only parses strings. You'll need to fetch the feed yourself.

**Comment by pietheinstrengholt** [comment]
Thanks, I got it working now. So far the new parser works really well 👍 
@rowanmanning, are there any features that are still missing when comparing your parser with danmactough's library?

**Comment by rowanmanning** [comment]
No I think this is feature-complete for most feed parsing needs but feel free to open an issue if you spot anything missing
