### ISSUE TITLE
Add the remaining properties that gofeed supports.

### ISSUE THREAD

**Issue by rowanmanning** [rowanmanning/feed-parser#91]
The API is based on [gofeed](https://github.com/mmcdole/gofeed). We still need to add support for a few properties:

## Feed

- [x] `authors`
- [x] `categories` (note: we need a sample with `atom:category` elements)

## Feed Item

- [x] `authors`
- [x] `categories` (note: we need a sample with `atom:category` elements)

**Comment by sunderee** [comment]
Hi, I have a questions regarding this library, and this issue in particular.

When you mention that the library is missing a lot of features, are those listed here the only ones left?

**Comment by rowanmanning** [comment]
Hi @sunderee, yep categories are the last thing to add, then I'm considering this feature-complete and will release a `v1.0.0`

**Comment by rowanmanning** [comment]
And we're done, categories have been added. I need to overhaul the unit tests because they're a nightmare but now we're feature-complete.

**Comment by sunderee** [comment]
Oh wow, great news!!! Thank you for your amazing and hard work!
